const data = {
  rating: [
    {
      id: '123',
      name: 'Владимир',
      lastName: 'Ларионов',
      img: './static/male.png',
      points: '463',
    },
    {
      id: '9',
      name: 'Владимир',
      lastName: 'Сергеев',
      img: './static/male.png',
      points: '521',
    },
    {
      id: '231',
      name: 'Вениамин',
      lastName: 'Васильев',
      img: './static/male.png',
      points: '865',
    },
    {
      id: '321',
      name: 'Мария',
      lastName: 'Логинова',
      img: './static/female.png',
      points: '865',
    },
    {
      id: '492',
      name: 'Борис',
      lastName: 'Казанцев',
      img: './static/male.png',
      points: '784',
    },
    {
      id: '452',
      name: 'Полина',
      lastName: 'Калинина',
      img: './static/female.png',
      points: '225',
    },
    {
      id: '796',
      name: 'Даниил',
      lastName: 'Воробьёв',
      img: './static/male.png',
      points: '642',
    },
    {
      id: '4',
      name: 'Эрик',
      lastName: 'Аксёнов',
      img: './static/male.png',
      points: '150',
    },
    {
      id: '1155',
      name: 'Иван',
      lastName: 'Иванов',
      img: './static/male.png',
      points: '100',
    },
    {
      id: '12145',
      name: 'Артем',
      lastName: 'Алексеев',
      img: './static/male.png',
      points: '1000',
    },
  ],
  friends: [
    {
      id: '9',
      name: 'Владимир2',
      lastName: 'Сергеев',
      img: './static/male.png',
    },
    {
      id: '4',
      name: 'Эрик',
      lastName: 'Аксёнов',
      img: './static/male.png',
    },
    {
      id: '15411',
      name: 'Ирина',
      lastName: 'Чеснокова',
      img: './static/female.png',
    },
    {
      id: '15564',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/female.png',
    },
    {
      id: '11111',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/male.png',
    },
    {
      id: '11112',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/female.png',
    },
    {
      id: '11113',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/male.png',
    },
    {
      id: '11114',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/female.png',
    },
    {
      id: '11115',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/male.png',
    },
    {
      id: '11116',
      name: 'Дарина',
      lastName: 'Боброва',
      img: './static/female.png',
    },
  ],
};

export default data;
